language: python
cache: pip

matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
sudo: true

python:
  - "3.7"

before_install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pygments
  - pip install pymdown-extensions
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs -V
  # - mkdocs gh-deploy --force --clean
  - mkdocs build --clean

branches:
  only:
- master